Better style in modgit and modprompt

diff --git a/modprompt b/modprompt
--- a/modprompt
+++ b/modprompt
@@ -7,7 +7,7 @@ function exit2msg_error_msg() {
     # Print error message 
     #   $1 = exit code, assumed to follow sysexit.h convention
     local errorno="$1"
-    case "$errorno" in
+    case "${errorno}" in
         0) echo "Success"  ;;
         1) echo "Miscellaneous/Syntax error"  ;;
         2) echo "Misuse of shell builtin"  ;;
@@ -66,9 +66,9 @@ function exit2msg_error_msg() {
       131) echo "Fatal error 2"  ;;
       148) echo "Stopped" ;;
       255) echo "Exit status out of range"  ;;
-        *) if (( "$errorno" > 128 && "$errorno" < 255 )); then
-              let errorno="errorno-128"
-              echo "Fatal error $errorno" 
+        *) if (( "${errorno}" > 128 && "${errorno}" < 255 )); then
+              (( errorno="errorno-128" ))
+              echo "Fatal error ${errorno}" 
            else
                echo "Unknown error" 
            fi
@@ -79,24 +79,34 @@ function exit2msg_error_msg() {
 function checkerr() {
     command=$(HISTTIMEFORMAT='' history 1 | sed 's/.*=.*//g' | awk '{print $2}')
     if [ "$1" != "0" ]; then
-        echo -e "\033[31;1m$PSERR  '$command': Exit code $(exit2msg_error_msg  $1) \033[0m\012\015"
+        message=$(exit2msg_error_msg "$1")
+        echo -e "\033[31;1m${PSERR}  '$command': Exit code ${message} \033[0m\012\015"
         echo ""
     else
-        echo -e "\033[32;1m$PSOK\033[0m\012\015"
+        echo -e "\033[32;1m${PSOK}\033[0m\012\015"
     fi   
 }
 
 PSSTYLE=${1:-checkmarks}
-case ${PSSTYLE} in
+case "${PSSTYLE}" in
     "thumbs")
         export PSERR="👎"
         export PSOK="👍"
-        export PS1='\[\033[0;37m\]$(checkerr $?)\[\033[34;0m\]<'${USER}'> \D{%F %T} \033[36;1m$(echo $(module --terse list 2>&1);true)\033[0m <$(git branch --show-current 2>/dev/null;true)$(printf '%.*s' $(git ls-files -m 2>/dev/null | wc -l) +)> \[\033[0m\]\n\[\033[34;1m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[0m\]\n\$ '
         ;;
     "checkmarks")
         export PSERR="❌"
         export PSOK="✅"
-        export PS1='\[\033[0;37m\]$(checkerr $?)\[\033[34;0m\]<'${USER}'> \D{%F %T} \033[36;1m$(echo $(module --terse list 2>&1);true)\033[0m <$(git branch --show-current 2>/dev/null;true)$(printf '%.*s' $(git ls-files -m 2>/dev/null | wc -l) +)> \[\033[0m\]\n\[\033[34;1m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[0m\]\n\$ '
         ;;
-    *) false;;
+    *)
+        export PSERR=""
+        export PSOK=""
+        false;;
 esac
+if [[ "${PSERR:-}" && "${PSOK:-}" ]]; then
+    # shellcheck disable=SC2125
+    export PS1='\[\033[0;37m\]$(checkerr $?)\[\033[34;0m\]<'${USER}'> \D{%F %T} \033[36;1m$(echo $(module --terse list 2>&1);true)\033[0m <$(git branch --show-current 2>/dev/null;true)$(printf '%.*s' $(git ls-files -m 2>/dev/null | wc -l) +)> \[\033[0m\]\n\[\033[34;1m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[0m\]\n\$ '
+else
+    echo "Not a valid style, use 'thumbs' or 'checkmarks'" 2>&1
+    export PS1="\h-\$ "
+    false
+fi
